### ISSUE TITLE
Is FreeSync/VRR supported?

### ISSUE THREAD

**Issue by Vinjul1704** [johanmalm/labwc#28] opened 2021-03-22 15:49 UTC
Hi, I am curious if FreeSync or VRR is supported? If not, is it planned?

Thanks!

**Comment by johanmalm** [comment] 2021-03-22 21:24
It's not current support. Happy to implement if not too hard.
It might be as simple as using wlr_output_enable_adaptive_sync()
Would you be happy to test if I implement?

**Comment by johanmalm** [comment] 2021-03-22 21:29
Could you try with

```
LAB_ADAPTIVE_SYNC=1 ./build/labwc
```

**Comment by Vinjul1704** [comment] 2021-03-23 00:28
Thanks a lot! Unfortunately my graphics card broke 2 days ago and I am waiting for a new one to arrive. I can test as soon as it's here.

**Comment by johanmalm** [comment] 2021-03-31 08:30
I've changed the environment variable name to LABWC_ADAPTIVE_SYNC for consistency.
I'll close this for now, but please let me know if you're able to test it at some point.

**Closed by johanmalm** 2021-03-31 08:30 UTC

**Comment by Vinjul1704** [comment] 2021-04-12 04:39
Sorry for the late reply, took longer than expected and I had to take care of a bunch of other stuff first.

I am not sure if it works, since I don't notice any tearing with and without the option as well as with a version before the commit. I tried it on a fresh Arch installation with just enough installed to get it running. Tried it with HDMI and DP and the GPU is an R9 290 in case that matters.

**Comment by Saladaa** [comment] 2021-06-11 08:08
After my exams next week, I will test this out with my monitor that has a VRR fps counter built in to confirm if this is working or not, assuming no one has (or will) confirmed it as working. I'd test it out now but I don't have labwc installed and I don't intend to use it (besides for testing this out), it's just good to see more compositors adopting variable refresh rate, especially to recommend to friends who want the feature but aren't into tiling WMs (i.e. Sway).

@Vinjul1704 if you're still interesting in confirming if the feature is working or not, ping me a week from now if I forget.
Also, you could try using [emersion/drm_monitor](https://github.com/emersion/drm_monitor) to test if VRR is working. I've used it in the past and it works great with my setup, but if you just let it run from the terminal on the freesync display do note that it'll force the display to its max refresh rate no matter if freesync is working or not due to how often it renders (see https://github.com/emersion/drm_monitor/issues/3)

**Comment by johanmalm** [comment] 2021-06-26 17:34
Thanks

**Comment by Consolatis** [comment] 2024-03-09 18:39
@Patola please stop with that abusive behavior. If you have a question like "Does labwc now support VRR" then ask that question instead. (The answer would be [yes](https://labwc.github.io/labwc-config.5.html#entry_core_adaptivesync)).
